### ISSUE TITLE
Was working yesterday.  Now displays (ERROR) and loading

### ISSUE THREAD

**Issue by JVTEAM** [taoteh1221/Open_Crypto_Portfolio_Tracker#17]
I had it running for a week now.  Now it no longer loads the markets and just displays ETH(Error) Loading... or BTC (Error) Loading...

**Comment by taoteh1221** [comment]
Being fixed already, but thanks for reporting: https://github.com/taoteh1221/Slideshow_Crypto_Ticker/pull/24
